#!/usr/bin/env bash
#
# Checks for out-of-date/broken locks

index_files=("`git diff --cached --name-only`")

for file in $index_files; do
  bad_lock="`git show :$file | lock_block -c | cut -d: -f3`"
  if [[ -n $bad_lock ]]; then
    bad_exit=true
    # lock_block operates on staged content; we want line numbers for physical files
    line="`grep -n \"lock do $bad_lock\" $file | cut -d: -f1`"
    locks=("${locks[@]} $file:$line:$bad_lock")
  fi
done

if [[ -n $bad_exit ]]; then
  echo -e "The following locks are broken:\n"
  for lock in $locks; do
    echo "  $lock"
  done
  echo -e "\nPlease fix them before committing."
  exit 1
fi
